version: '3.7'

services:
  psp-postgresql: 
    image: postgres:latest
    environment: 
      POSTGRES_DB: 'PSP'
      POSTGRES_USER: 'databaseuser'
      POSTGRES_PASSWORD: 'databasepassword'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init-files:/docker-entrypoint-initdb.d
    networks:
      - postgres-pgadmin-network

  pgadmin-psp:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
    ports:
      - "8000:80"
    networks:
      - postgres-pgadmin-network

networks:
  postgres-pgadmin-network:

volumes:
  postgres-data:


